import type { GalleryUseCase } from "@/features/gallery/types";

export const galleryUseCases: GalleryUseCase[] = [
  {
    id: 101,
    title: "Autotranslation using AWS translation",
    phase: "Diagnose",
    status: "Submitted",
    businessUnit: "Communications",
    team: "Content Ops",
    subTeam: "Localization",
    vendorName: "Poppulo AI",
    aiModel: "Poppulo Model A",
    aiThemes: ["Audio Generation", "Causal AI"],
    personas: ["All"],
    bgColor: "#c7e7e7",
    headline: "Streamline multilingual communication through AI translation.",
    opportunity: "Enable faster, consistent translation of global content at scale.",
    evidence: "High translation backlog and inconsistent turnaround times.",
    primaryContact: "Ava Chen, ava.chen@example.com",
  },
  {
    id: 102,
    title: "Ready Implementation - Check History Chatbot",
    phase: "Idea",
    status: "Draft",
    businessUnit: "Engineering",
    team: "Platform",
    subTeam: "Developer Experience",
    vendorName: "Azure AI",
    aiModel: "GPT-4",
    aiThemes: ["Conversational AI"],
    personas: ["Developer"],
    bgColor: "#e8d5c4",
    headline: "Answer check history questions with an internal chatbot.",
    opportunity: "Reduce time engineers spend searching for historical context.",
    evidence: "Frequent Slack questions and repeated onboarding tickets.",
    primaryContact: "Noah Patel, noah.patel@example.com",
  },
  {
    id: 103,
    title: "SharePoint Assistant for IT Helpdesk",
    phase: "Implemented",
    status: "Approved",
    businessUnit: "IT",
    team: "End User Services",
    subTeam: "Support",
    vendorName: "Azure AI",
    aiModel: "GPT-4o",
    aiThemes: ["Intelligent Document Processing"],
    personas: ["Admin", "Support"],
    bgColor: "#d5e5d5",
    headline: "Summarize and route SharePoint tickets automatically.",
    opportunity: "Speed up ticket triage and reduce manual review time.",
    evidence: "Growing ticket volume and longer response SLAs.",
    primaryContact: "Liam Stone, liam.stone@example.com",
  },
  {
    id: 104,
    title: "AI-assisted Knowledge Base Tagging",
    phase: "Design",
    status: "Submitted",
    businessUnit: "Customer Success",
    team: "Knowledge",
    subTeam: "Content",
    vendorName: "OpenAI",
    aiModel: "o1-mini",
    aiThemes: ["Data Extraction", "Semantic Search"],
    personas: ["Content Strategist"],
    bgColor: "#f0e2f5",
    headline: "Auto-tag KB articles to improve findability.",
    opportunity: "Increase article discovery and reduce duplicated content.",
    evidence: "Users struggle to find the right articles quickly.",
    primaryContact: "Priya Singh, priya.singh@example.com",
  },
  {
    id: 105,
    title: "Candidate Screening Summaries",
    phase: "Diagnose",
    status: "Draft",
    businessUnit: "People",
    team: "Talent Acquisition",
    subTeam: "Recruiting Ops",
    vendorName: "OpenAI",
    aiModel: "GPT-4.1",
    aiThemes: ["Summarization"],
    personas: ["Recruiter"],
    bgColor: "#dce7ff",
    headline: "Summarize resumes and interviews for faster screening.",
    opportunity: "Reduce manual review time and improve screening consistency.",
    evidence: "High volume of roles with time-intensive screening steps.",
    primaryContact: "Sophia Lee, sophia.lee@example.com",
  },
  {
    id: 106,
    title: "Sales Enablement Pitch Generator",
    phase: "Idea",
    status: "Submitted",
    businessUnit: "Sales",
    team: "Enablement",
    subTeam: "Field",
    vendorName: "Anthropic",
    aiModel: "Claude 3.5",
    aiThemes: ["Content Generation"],
    personas: ["Sales Rep"],
    bgColor: "#f5edd2",
    headline: "Generate tailored pitch outlines for target accounts.",
    opportunity: "Accelerate pitch creation and improve personalization.",
    evidence: "Inconsistent messaging across regional teams.",
    primaryContact: "Maya Brooks, maya.brooks@example.com",
  },
];
